# Generated by Django 6.0.4 on 2026-06-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_first_name_customuser_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="registration_source",
            field=models.CharField(default="local", max_length=50),
        ),
    ]
